---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: first-app
spec:
  hosts:
    - api.on-boarding.infra.adeptmind.net
    - first-app
  gateways:
    - api
  http:
    - name: first-app
      route:
        - destination:
            host: first-app
            subset: v1
          weight: 90
        - destination:
            host: first-app
            subset: v2
          weight: 10
