apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-adapter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-adapter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: search-adapter
    spec:
      - name: app
        image: gcr.io/retail-364515/infra-dashboard-api:e3f3681aae51071118f390dbb96c6520e1795a22
        env:
        - name: APP_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: infra-dashboard-api-configmap
              key: APP_DOMAIN
        - name: API_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: infra-dashboard-api-configmap
              key: API_DOMAIN
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: infra-dashboard-api-configmap
              key: ALLOWED_HOSTS
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: infra-dashboard-api-configmap
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: infra-dashboard-api-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: infra-dashboard-api-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: infra-dashboard-api-configmap
              key: DB_PASSWORD
        - name: GIT_TOKEN
          valueFrom:
            configMapKeyRef:
              name: infra-dashboard-api-configmap
              key: GIT_TOKEN
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
  
